version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Bağımlılıklar yükleniyor...
      - npm install
  build:
    commands:
      - echo Build işlemi başladı...
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build